### ISSUE TITLE
Type 7 records Not being written with EbtsBuilder

### ISSUE THREAD

**Issue by mywill** [ebts/jet#7]
When using the EbtsBuilder.build when it checks what builder to use using the genericTypes (1,2,9,10,13,14,15,16,17) and binaryHeaderTypes (3,4,5,6) Type 7 records are not in either set.  Is their a reason why 7 is not in the binaryHeaderTypes?

**Comment by adamday2** [comment]
Type 7 is excluded from the binaryHeaderTypes due to some complications regarding the lack of consistency in data and the formats of data that is actually stored in the Type 7 across various organizations.

There is another open issue regarding this. I'm planning a fix for this which will enable a flag (likely during parsing) to treat type 7 as a binary type with simple header (e.g., length, IDC). Haven't had much time for maintenance of this project recently, but will try to carve out some time this week for a fix.

**Comment by adamday2** [comment]
I thought this was an issue to deal with Type 7 handling at first (which is finicky), but this is definitely a bug. I'll push a fix for it.

**Comment by jej2003** [comment]
@adamday2 , any update on this? We can look to implement if you want to provide details as to how to address

**Comment by adamday2** [comment]
Going to try to patch this evening.

It should just be an update to:
https://github.com/ebts/jet/blob/master/Jet/src/main/java/org/mitre/jet/ebts/EbtsUtils.java to add 7 to the binaryHeader set.

**Comment by adamday2** [comment]
@mywill I just landed a fix for this. Try it out and let me know how it works.

**Comment by mywill** [comment]
@adamday2 When i attempt to parse it now i get this:
`Caused by: java.lang.UnsupportedOperationException: Unable to predict header from this record, use alternate constructor.`
It seems to be because the check to the BINARY_HEADER_RECORD_TYPES in the EbtsParser happens before the specific logic for the Type 7 and Type 8 binary fields.   If i update to move the if checks the parsing works but the build writes a unreadable file. The following code fails with the two byte arrays being 107 different in length for the test eft i was using.

`byte[] og = Files.readAllBytes( Paths.get(path) );
        Ebts x = EbtsParser.parse( og, ParseType.FULL, EbtsParser.Type7Handling.TREAT_AS_TYPE4 );
        EbtsBuilder eb = new EbtsBuilder(  );
        byte[] b = eb.build( x );
        Ebts x2 = EbtsParser.parse( b, ParseType.FULL, EbtsParser.Type7Handling.TREAT_AS_TYPE4);
        System.out.print( "" );`

**Comment by adamday2** [comment]
@mywill I just pushed a new update along with a few new test cases. Let me know if this fixes the length issue you are seeing. There might still be some problems surrounding the headers that I haven't yet tracked down.

We're a little short on test data at the moment. If you have a sharable test file that you can contribute that hits this use case, would be happy to create some test cases around it.

**Comment by mywill** [comment]
@adamday2 This seems to work for me now.  I still have a slightly different byte length after i write using the builder i will have to try and create a sharable eft to demonstrate that but i can read the files i write now.
